#ifndef PACKET_INFO_HPP
#define PACKET_INFO_HPP
    #define GIMBAL_ANGLE_SET_PACKET_ID 0x05
    #define GIMBAL_ANGLE_SET_PACKET_SIZE 10
    #define GIMBAL_ANGLE_FDB_PACKET_ID 0x06
    #define GIMBAL_ANGLE_FDB_PACKET_SIZE 8
    #define ENEMY_COLOR_PACKET_ID 0x07
    #define ENEMY_COLOR_PACKET_SIZE 1
    #define RELATIVE_ANGLE_PACKET_ID 0x09
    #define RELATIVE_ANGLE_PACKET_SIZE 4
    #define DATA_RECORD_PACKET_ID 0x10
    #define DATA_RECORD_PACKET_SIZE 4
#endif